name: lms
channels:
  - defaults
dependencies:
  - ca-certificates=2019.5.15=1
  - certifi=2019.6.16=py37_1
  - openssl=1.1.1d=he774522_0
  - pip=19.2.2=py37_0
  - pymongo=3.8.0=py37ha925a31_1
  - python=3.7.4=h5263a28_0
  - setuptools=41.0.1=py37_0
  - sqlite=3.29.0=he774522_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_0
  - wheel=0.33.4=py37_0
  - wincertstore=0.2=py37_0
prefix: D:\ProgramInstalls\Anaconda\envs\lms

